if(ATTINY_DEVICE STREQUAL "attiny414")
    set(AVR_MCU attiny414)
    set(FLASH_SIZE 4096)
elseif(ATTINY_DEVICE STREQUAL "attiny1624")
    set(AVR_MCU attiny1624)
    set(FLASH_SIZE 16384)
elseif(ATTINY_DEVICE STREQUAL "attiny1626")
    set(AVR_MCU attiny1626)
    set(FLASH_SIZE 16384)
else()
    message(FATAL_ERROR "invalid part: ${ATTINY_DEVICE}")
endif()
